wmtech/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
import main.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main.views.home, name='home'),
    path('login/', main.views.login, name='login'),
    path('galerie/', main.views.gallery, name='gallery'),
    path('impressum/', main.views.impressum, name='impressum'),
    path('privacy-policy/', main.views.privacy_policy, name='privacy_policy'),
    path('produkt/<int:pk>', main.views.single_product, name='single_product'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe

# Create your models here

class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    card_image = models.ForeignKey(
            'Image', 
            on_delete=models.SET_NULL, 
            null=True, 
            blank=True, 
            related_name='card_image_for_product'
        )

    def __str__(self):
        return self.name
    
    def get_images(self):
        return Image.objects.filter(product=self)
    
    class Meta:
        verbose_name_plural = "Projects"
        verbose_name = "Project"


class Image(models.Model):
    image = models.ImageField(upload_to='products/')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.product.name} - {self.pk}'
    
    def img_preview(self): 
        return mark_safe(f'<img src = "{self.image.url}" width = "200"/>')

class Page(models.Model):
    PAGES = [
        ('home', 'Home'),
        ('impressum', 'Impressum'),
        ('legal', 'Datenschutzerklärung'),
    ]
    title = models.CharField(max_length=200)
    content = models.TextField(null=True)
    page = models.CharField(max_length=10, choices=PAGES)

    def __str__(self):
        return self.title


class Feature(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    sequence = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['sequence']
    
class Section(models.Model):
    SECTIONS = [
        ('projects', 'Projekte'),
        ('features', 'Features'),
        ('about', 'Über Uns'),
        ('contact', 'Kontakt'),
    ]
    title = models.CharField(max_length=200)
    subtitle = models.TextField()
    background_image = models.ImageField(upload_to='sections/', null=True, blank=True)
    section = models.CharField(max_length=10, choices=SECTIONS, unique=True)

    def __str__(self):
        return self.title
    
    def img_preview(self): 
        return mark_safe(f'<img src = "{self.background_image.url}" width = "200"/>')

main/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3


class ContactForm(forms.Form):
    prename = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-main focus:border-main'}))
    name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-main focus:border-main'}))
    email = forms.EmailField(max_length=254, required=True,  widget=forms.TextInput(attrs={'class': 'block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-main focus:border-main'}))
    phone = forms.CharField(max_length=20, required=False,  widget=forms.TextInput(attrs={'class': 'block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-main focus:border-main'}))
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-main focus:border-main'}))
    captcha = ReCaptchaField(widget=ReCaptchaV3(), label=False, error_messages={
        'inv': 'reCaptcha-Validierung fehlgeschlagen. Bitte versuche Sie s später noch einmal oder kontaktieren Sie mich via anfrage@wenger-metalltechnik.ch, wenn das Problem weiterhin besteht.'
    })

main/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponseRedirect
from .models import Product, Feature, Section, Image, Page
from .forms import ContactForm
from wmtech import settings


# Create your views here.

def home(request):
    products = Product.objects.all()
    page = Page.objects.get(page='home')
    features = Feature.objects.all()
    feature_section = Section.objects.get(section='features')
    contact_section = Section.objects.get(section='contact')
    project_section = Section.objects.get(section='projects')
    about_section = Section.objects.get(section='about')
    submitted = False
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject, from_email, to = 'Kontaktformular Webseite', settings.EMAIL_HOST_USER, settings.EMAIL_HOST_USER
            html_content = render_to_string('email.html', {'prename': cd['prename'], 'name': cd['name'], 'email':cd['email'], 'message':cd['message']})
            text_content = render_to_string('email.txt', {'prename': cd['prename'], 'name': cd['name'], 'email':cd['email'], 'message':cd['message']})
                
            msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
            msg.attach_alternative(html_content, "text/html")
            msg.send()
            return HttpResponseRedirect('?submitted=True#contact')

    else:
        form = ContactForm()
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'home.html', {'products': products, 'features': features, 'form': form, 'feature_section': feature_section, 'contact_section': contact_section, 'project_section': project_section,'about_section': about_section, 'page': page, 'submitted': submitted})

def single_product(request, pk):
    product = Product.objects.get(pk=pk)
    images = product.get_images()
    return render(request, 'single-project.html', {'product': product, 'images': images})


def login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/admin/')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            auth_login(request, user)
            return HttpResponseRedirect('/admin/')
        else:
            return HttpResponseRedirect('login/')
    return render(request, 'login.html')


def gallery(request):
    images = Image.objects.all()
    return render(request, 'gallery.html', {'images': images})

def impressum(request):
    page = Page.objects.get(page='impressum')
    return render(request, 'legal.html', {'page': page})

def privacy_policy(request):
    page = Page.objects.get(page='legal')
    return render(request, 'legal.html', {'page': page})

main/templates/email.html
<h2>Du hast eine Nachricht über das Kontaktformular der Webseite Wenger Metalltechnik erhalten!</h2>
<div>
    <div>Die Nachricht ist von:
      <p><span>Vorname: </span><span>{{ prename }}</span></p>
      <p><span>Nachname: </span><span>{{ name }}</span></p>
      <p><span>E-Mail Adresse: </span><span>{{ email }}</span></p>
      <p><span>Phone: </span><span>{{ phone }}</span></p>
 	</div>
  
  	<h3>Nachricht</h3>
    <p>{{ message }}</p>
</div>

main/templates/gallery.html
{% extends 'page.html' %}{% load static %} 

{% block main %}
<section class="bg-white antialiased mt-12">
    <div class="max-w-screen-xl px-4 py-8 mx-auto lg:px-6">
        <div class="mt-16">
        <!-- Image Grid -->
        <h2 class="mt-2 text-3xl font-bold mb-10 pb-2 tracking-tight border-b text-gray-900 sm:text-4xl">Gallerie</h2>
            <div class="grid grid-cols-2 sm:grid-cols-3 gap-2">
                {% for image in images %}
                <a data-lightbox="gallery" class="group block relative overflow-hidden rounded-lg" href="{{ image.image.url }}">
                    <img class="w-full size-60 object-cover bg-gray-100 rounded-lg" src="{{ image.image.url }}" alt="Gallerie Image">
                    <div class="absolute bottom-1 end-1 opacity-0 group-hover:opacity-100 transition">
                      <div class="flex items-center gap-x-1 py-1 px-2 bg-white border border-gray-200 text-gray-800 rounded-lg dark:bg-neutral-900 dark:border-neutral-700 dark:text-neutral-200">
                        <svg class="shrink-0 size-3" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>
                        <span class="text-xs">View</span>
                      </div>
                    </div>
                  </a>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block scripts %}
<script src="{% static 'node_modules/lightbox2/src/js/lightbox.js' %}"></script>
{% endblock %}

main/templates/legal.html
{% extends 'page.html' %}
{% load markdown_extras %}
{% block main %}
<div class="h-[88px] bg-gray-900">

</div>
<div class="max-w-screen-xl px-4 py-8 mx-auto lg:px-6 sm:py-16 lg:py-24">
    <div class="max-w-3xl">
        <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl mb-4">{{ page.title }}</h2>
        <div class="h3:text-main h2:text-main h2:text-xl h2:font-bold p:mb-3">
            {{ page.content | convert_markdown | safe }}
        </div>
        
    </div>
</div>

{% endblock %}

main/templates/login.html
{% load compress %} {% load static %}
<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <!-- social Media Tags -->
        <meta property="og:title" content="Hexacoding" />
        <meta
            property="og:description"
            content="Dein Partner für Webseiten, Software und IT Projekte" />
        <meta
            property="og:image"
            content="https://hexacoding.ch/media/public/logo-with-bg.png" />
        <meta property="twitter:title" content="Hexacoding" />
        <meta
            property="twitter:description"
            content="Dein Partner für Webseiten, Software und IT Projekte" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta
            property="twitter:image"
            content="https://hexacoding.ch/media/public/logo-with-bg.png" />

        <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="../../media/favicon/apple-touch-icon.png" />
        <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="../../media/favicon/favicon-32x32.png" />
        <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="../../media/favicon/favicon-16x16.png" />
        <link rel="manifest" href="../../media/favicon/site.webmanifest" />
        <link
            rel="mask-icon"
            href="../../media/favicon/safari-pinned-tab.svg"
            color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />

        {% compress css %}
        <link rel="stylesheet" href="{% static 'src/output.css' %}" />
        {% endcompress %}

        <link rel="stylesheet" href="{% static 'src/index.css' %}" />
        <link rel="stylesheet" href="https://use.typekit.net/zct6qxu.css" />
        <script src="{% static 'scripts/index.js' %}"></script>
        
        <title>Hexacoding</title>
    </head>

<body>
    

<main class="bg-gray-900">
    <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
       
        <img class="w-40 mb-10" src="../../media/public/logo.svg" alt="logo"> 

        <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0">
            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl">
                    Sign in to your account
                </h1>
                <form class="space-y-4 md:space-y-6" method="POST">
                    {% csrf_token %}
                    <div>
                        <label for="username" class="block mb-2 text-sm font-medium text-gray-900">Benutzername</label>
                        <input type="text" name="username" id="username" class="bg-gray-50 border border-gray-300 text-gray-900 rounded-lg block w-full p-2.5" placeholder="" required="">
                    </div>
                    <div>
                        <label for="password" class="block mb-2 text-sm font-medium text-gray-900">Password</label>
                        <input type="password" name="password" id="password" placeholder="" class="bg-gray-50 border border-gray-300 text-gray-900 rounded-lg block w-full p-2.5" required="">
                    </div>
                    <button type="submit" class="w-full text-white bg-main hover:bg-main-dark font-medium rounded-lg text-sm px-5 py-2.5 text-center">Login</button>
                
                </form>
            </div>
        </div>
    </div>
</main>  

</body>
</html>

main/templates/page.html
{% load compress %} {% load static %} 

<!DOCTYPE html>
<html class="scroll-smooth scroll-py-48" lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% compress css %}
        <link rel="stylesheet" href="{% static 'src/output.css' %}" />
    {% endcompress %}
    <link rel="stylesheet" href="../../static/src/index.css">
    <link rel="stylesheet" href="../../static/node_modules/lightbox2/dist/css/lightbox.css">
    <title>Wenger Metalltechnik</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>
<body>
    <!-- ========== HEADER ========== -->
    {% include 'template_parts/header.html' %}
    <!-- ========== END HEADER ========== -->
    {% block main %}

    {% endblock %}
<!-- ========== FOOTER ========== -->
<footer class="mt-auto w-full py-10 px-4 sm:px-6 lg:px-8 mx-auto bg-gray-900">
  
  <div class="grid md:grid-cols-3 grid-cols-1 gap-y-10 max-w-[85rem] mx-auto">
    <div class="md:text-start text-center mt-10">
      <h3 class="mb-6 text-sm font-semibold uppercase text-white">Partner</h3>
        <ul>
          <li><a class="text-gray-500 hover:underline" href="https://metall-classics.ch/">Metall Classics</a></li>
          <li><a class="text-gray-500 hover:underline" href="https://hexacoding.ch/">Hexacoding</a></li>
        </ul>
    </div>
    <div class="text-center">
      <div class="flex justify-center">
        <img class="h-16" src="../../media/public/logo.svg">
      </div>
  

      <div class="mt-3">
        <h3 class="mb-2 mt-4 text-sm font-semibold uppercase text-white">Wenger Metalltechnik</h3>
        <p class="text-gray-500">Hauptstrasse 89</p>
        <p class="text-gray-500">4437 Waldenburg</p>
      </div>
      <h3 class="mt-4 text-sm font-semibold uppercase text-white">Kontakt</h3>
      <div>
        <p class="text-gray-500"><a href="mailto:anfrage@wenger-metalltechnik.ch" class="font-semibold hover:underline">anfrage@wenger-metalltechnik.ch</a></p>
        <p class="text-gray-500"><a href="tel:+41796685678" class="font-semibold hover:underline">079 668 56 78</a></p>
      </div>

      <p class="text-gray-500 mt-6">
        © {% now "Y" %} Wenger Metalltechnik.
      </p>
      <div class="mt-3">
        <p class="text-gray-500">Made by <a href="https://hexacoding.ch/" class="font-semibold hover:underline">Hexacoding</a></p>
      </div>
    </div>
    <div class="md:text-end text-center justify-end items-end mt-10">
      <h3 class="mb-6 text-sm font-semibold uppercase text-white">Rechtliches</h3>
      <ul>
        <li><a class="text-gray-500 hover:underline" href="{% url 'impressum' %}">Impressum</a></li>
        <li><a class="text-gray-500 hover:underline" href="{% url 'privacy_policy' %}">Datenschutzerklärung</a></li>
      </ul>
    </div>
</div>
  
  <!-- End Grid -->
</footer>
<!-- ========== END FOOTER ========== -->
    <script src="{% static 'index.js' %}"></script>
    <script src="{% static 'node_modules/flowbite/dist/flowbite.min.js' %}"></script>
    <script src="{% static 'node_modules/preline/dist/preline.js' %}"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

main/templates/single-project.html
{% extends 'page.html' %}{% load static %} 

{% block main %}
<section class="bg-white antialiased mt-12">
    <div class="max-w-screen-xl px-4 py-8 mx-auto lg:px-6">
        <section class="bg-white">
            <div class="gap-16 items-center py-8 px-4 mx-auto max-w-screen-xl lg:grid lg:grid-cols-2 lg:py-16 lg:px-6">
                <div class="font-light text-gray-500 sm:text-lg dark:text-gray-400">
                    <h2 class="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">{{ product.name }}</h2>
                    <p class="mt-4">{{ product.description }}</p>
                </div>
                <div>
                    <img class="w-full mt-10 aspect-[16/9] rounded-lg" src="{{ product.card_image.image.url }}" alt="office content 1">
                </div>
            </div>
        </section>

        <div class="mt-16">
        <!-- Image Grid -->
            <h3 class="text-base font-semibold leading-6 text-gray-900 mb-6 border-b border-gray-200 pb-5">Gallerie</h3>
            <div class="gap-4 mt-8 grid sm:grid-cols-4 sm:mt-12 grid-cols-2">
                {% for image in images %}
                    {% if forloop.counter|divisibleby:6 or forloop.counter|divisibleby:4 or forloop.counter|divisibleby:3 or forloop.counter|divisibleby:2 %}
                        <a class="sm:col-span-1 w-full h-72 object-cover rounded-lg" data-lightbox="{{ product.name }}" href="{{ image.image.url }}"><img class="w-full h-72 object-cover rounded-lg" src="{{ image.image.url }}" alt=""></a>
                    {% else %}
                    <a class="sm:col-span-2 w-full h-72 object-cover rounded-lg" data-lightbox="{{ product.name }}" href="{{ image.image.url }}"><img data-lightbox="{{ product.name }}" class="sm:col-span-2 w-full h-72 object-cover rounded-lg" src="{{ image.image.url }}" alt=""></a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block scripts %}
<script src="{% static 'node_modules/lightbox2/src/js/lightbox.js' %}"></script>
{% endblock %}

main/templates/template_parts/contact.html
<section class="bg-white mt-32">
    <div class="relative bg-gray-700 bg-blend-multiply">
        <!-- Replace background image with an img tag -->
        <img src="{{ contact_section.background_image.url }}" 
             alt="Contact Background"
             class="w-full h-full object-cover absolute inset-0 z-0">

        <!-- Content container, with z-index to appear above the image -->
        <div id="contact"  class="relative px-4 lg:pt-24 pt-8 pb-72 lg:pb-80 mx-auto w-full text-center lg:px-6 bg-gray-900 bg-opacity-90">
            <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-white">{{ contact_section.title }}</h2>
            <p class="mb-16 font-light text-gray-400 sm:text-xl">{{ contact_section.subtitle }}</p>
        </div> 
    </div>
    <div class="py-16 px-4 mx-auto -mt-96 max-w-screen-xl sm:py-24 lg:px-6 z-10 flex flex-col relative">
        {% if submitted %}
                    <div class="relative isolate overflow-hidden bg-gray-900 py-24 sm:py-32 rounded-3xl shadow-2xl">
                        <div class="hidden sm:absolute sm:-top-10 sm:right-1/2 sm:-z-10 sm:mr-10 sm:block sm:transform-gpu sm:blur-3xl" aria-hidden="true">
                          <div class="aspect-[1097/845] w-[68.5625rem] bg-gradient-to-tr from-[#1B2741] to-[#776fff] opacity-20" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
                        </div>
                        <div class="absolute -top-52 left-1/2 -z-10 -translate-x-1/2 transform-gpu blur-3xl sm:top-[-28rem] sm:ml-16 sm:translate-x-0 sm:transform-gpu" aria-hidden="true">
                          <div class="aspect-[1097/845] w-[68.5625rem] bg-gradient-to-tr from-[#1B2741] to-[#776fff] opacity-20" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
                        </div>
                        <div class="mx-auto max-w-7xl px-6 lg:px-8">
                          <div class="mx-auto max-w-2xl lg:mx-0">
                            <h2 class="text-4xl font-bold tracking-tight text-white sm:text-6xl">Anfrage gesendet</h2>
                            <p class="mt-6 text-lg leading-8 text-gray-300">Vielen Dank für Ihre Anfrage! Wir werden uns so schnell wie möglich bei Ihnen melden.</p>
                          </div>
                        </div>
                      </div>
                {% else %}
        <form method="POST" class="grid grid-cols-1 gap-8 p-6 mx-auto mb-16 max-w-screen-md bg-white rounded-lg border border-gray-200 shadow-sm lg:mb-28 sm:grid-cols-2">
            {% csrf_token %}
            <div>
                <label for="id_prename" class="block mb-2 text-sm font-medium text-gray-900 after:content-['*'] after:ml-0.5 after:text-red-500">Vorname</label>
                {{ form.prename }}
            </div>
            <div>
                <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 after:content-['*'] after:ml-0.5 after:text-red-500">Name</label>
                {{ form.name }}
            </div>
            <div>
                <label for="id_email" class="block mb-2 text-sm font-medium text-gray-900 after:content-['*'] after:ml-0.5 after:text-red-500">Email</label>
                {{ form.email }}
                {% if form.email.errors %}
                    <div class="text-red-600 text-sm mt-1">
                        {% for error in form.email.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div>
                <label for="id_phone" class="block mb-2 text-sm font-medium text-gray-900">Telefonnummer:</label>
                {{ form.phone }}
            </div>
            <div class="sm:col-span-2">
                <label for="id_message" class="block mb-2 text-sm font-medium text-gray-900 after:content-['*'] after:ml-0.5 after:text-red-500">Nachricht</label>
                {{ form.message }}
                <p class="mt-4 text-sm text-gray-500">Mit dem Absenden dieses Formulars erklären Sie sich mit unserer <a href="{% url 'privacy_policy' %}" class="text-main underline">Datenschutzrichtlinie</a> einverstanden, in der erläutert wird, wie wir Ihre persönlichen Daten erfassen.</p>
            </div>
            {{ form.captcha }}
            <button type="submit" class="py-3 px-5 text-sm font-medium text-center text-white rounded-lg bg-main sm:w-fit hover:bg-main">Nachricht senden</button>
        </form>
        {% endif %}
        <div class="space-y-8 text-center md:grid md:grid-cols-2 lg:grid-cols-3 md:gap-12 md:space-y-0 {% if submitted %}mt-16{% endif %}">
            <div>
                <div class="flex justify-center items-center mx-auto mb-4 w-10 h-10 bg-gray-100 rounded-lg lg:h-16 lg:w-16">
                    <svg class="w-5 h-5 text-gray-600 lg:w-8 lg:h-8" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z"></path><path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z"></path></svg>
                </div>
                <p class="mb-2 text-xl font-bold">Email:</p>
                <p class="mb-3 text-gray-500">Schreiben Sie uns eine E-Mail, wenn Sie allgemeine Fragen haben.</p>
                <a href="mailto:anfrage@wenger-metalltechnik.ch" class="font-semibold text-main hover:underline">anfrage@wenger-metalltechnik.ch</a>
            </div>
            <div>
                <div class="flex justify-center items-center mx-auto mb-4 w-10 h-10 bg-gray-100 rounded-lg lg:h-16 lg:w-16">
                    <svg class="w-5 h-5 text-gray-600 lg:w-8 lg:h-8" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 3a1 1 0 011-1h2.153a1 1 0 01.986.836l.74 4.435a1 1 0 01-.54 1.06l-1.548.773a11.037 11.037 0 006.105 6.105l.774-1.548a1 1 0 011.059-.54l4.435.74a1 1 0 01.836.986V17a1 1 0 01-1 1h-2C7.82 18 2 12.18 2 5V3z"></path></svg>
                </div>
                <p class="mb-2 text-xl font-bold">Telefon:</p>
                <p class="mb-3 text-gray-500">Rufen Sie uns an und sprechen Sie direkt mit einem Mitglied unseres Teams. Wir helfen Ihnen immer gerne weiter.</p>
                <a href="tel:+41796685678" class="font-semibold hover:underline text-main">079 668 56 78</a>
            </div>
            <div>
                <div class="flex justify-center items-center mx-auto mb-4 w-10 h-10 bg-gray-100 rounded-lg lg:h-16 lg:w-16">
                    <svg class="w-5 h-5 text-gray-600 lg:w-8 lg:h-8" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4 4a2 2 0 012-2h8a2 2 0 012 2v12a1 1 0 110 2h-3a1 1 0 01-1-1v-2a1 1 0 00-1-1H9a1 1 0 00-1 1v2a1 1 0 01-1 1H4a1 1 0 110-2V4zm3 1h2v2H7V5zm2 4H7v2h2V9zm2-4h2v2h-2V5zm2 4h-2v2h2V9z" clip-rule="evenodd"></path></svg>
                </div>
                <p class="mb-2 text-xl font-bold">Adresse:</p>
                <p class="text-gray-500">Wenger Metalltechnik</p>
                <p class="text-gray-500">Hauptstrasse 89</p>
                <p class="text-gray-500">4437 Waldenburg</p>
                <a href="https://maps.app.goo.gl/zQypogQ3iaE4ni9i7" target="_blank" class="inline-flex py-2 px-4 mt-4 text-sm font-medium text-center rounded-lg border text-main border-main hover:text-white hover:bg-main focus:ring-4 focus:outline-none focus:ring-main-light">Google Maps</a>
            </div>
        </div>
    </div>
</section>